### ISSUE TITLE
Add ability to create snapshot of separated element on a page

### ISSUE THREAD

**Issue by idem7x** [saucelabs/visual-examples#98]
With current approach you make full page screenshot and give ability to ignore some elements on a page. 
But sometimes you need to check only one element on page, not the full page. 

Would be cool to have something like **checkElement** like here - https://github.com/wswebcreation/webdriver-image-comparison/blob/main/docs/OPTIONS.md#method-options

**Comment by FriggaHel** [comment]
Hi @idem7x,

That's not currently implemented but this is on our roadmap and will come in 2024.

**Comment by omacranger** [comment]
Hey there, I see this is an old issue but this has been resolved for some time! For webdriver frameworks you can clip to an element by passing `clipElement` and for local frameworks (Storybook, Cypress, etc) you can use a `clipSelector`. Check the docs for your specific framework for more details / how to, but here's the [example for WDIO](https://docs.saucelabs.com/visual-testing/integrations/webdriverio/#clip-to-an-element).
